Awesome store 💯
SimonGideon/awesome-books pull request #1
Opened 2022-10-27 12:26 UTC by SimonGideon

In this PR I:

1. Create a collection that keeps a list of books (hint: you can use an array of objects for that).
2. Create a function to add a new book to the collection, with title and author.
3. Create a function to remove a book from the collection 
4. Display all books saved in the collection in the top part of the page.
5. Make sure that when a user clicks the "Add" button:
6. A new book is added to the collection.
7. The new book is displayed in the page.
8. Make sure that when a user clicks the "Remove" button:
9. The correct book is removed from the collection.
10. The correct book disappears from the page.

2022-10-27 19:48 UTC, nicupop729 requested changes
Hi @SimonGideon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
 - [X] Correct GitHub flow practice :heavy_check_mark:
 - [X] Good commit messages :heavy_check_mark:
 - [X] Linters are passing :heavy_check_mark:
 - [X] Clean codebase :heavy_check_mark:


## Required Changes ♻️
I understand that you were not with your team members from the beginning and that you built this project alone.
Because of this reason, I didn't invalidate your project for not having a README file, but as this aspect is very important, I will need to ask it as MANDATORY.

- [ ] please built your README file using the [Microverse README template](https://github.com/microverseinc/readme-template).

- [ ] _Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 19:48 UTC, nicupop729 commented on index.js
> +const BooksObj = JSON.parse(localStorage.getItem('books'));
On refresh, all the books disappear from the UI and the array of books is emptied. This is something that we want to avoid so that the user can add books later on to the list of books he already has.
As the project requirements mention, the data must be preserved in the browser's memory.
![image](https://user-images.githubusercontent.com/83596135/198383539-82f24996-8ba1-47c1-b80a-11f44128a4fc.png)

- [ ] Kindly, refactor the code so that on refresh the data is preserved.

2022-10-27 22:22 UTC, SimonGideon commented on index.js
> +displayBook();
@nicupop729 :smile: Thanks for this I had to go back and check how to refactor my code and found a wonderful and simplest way to this section which I didn't know but now I have leaned it. :+1:

2022-10-27 22:29 UTC, SimonGideon commented on index.js
> +});
@nicupop729 :100: This has been implemented as requested: check out on :point_right: https://github.com/SimonGideon/awesome-books/pull/1/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R51-R52

2022-10-27 22:32 UTC, SimonGideon commented on index.js
> +const BooksObj = JSON.parse(localStorage.getItem('books'));
### @nicupop729 :100: :1st_place_medal: 
This has been solved and worked as expected. Thanks for the suggested changes. See this change on :point_right: https://github.com/SimonGideon/awesome-books/pull/1/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R12-R25

2022-10-28 07:34 UTC, medaminedev66 approved these changes
Hi @SimonGideon 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- The user is able to add books.
- The added books are saved in the local storage.
- The books are loaded from the local storage and displayed on the page after reloading the page.
Great work 👏 

### Optional suggestions
- Check the comment below this review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 07:34 UTC, medaminedev66 commented on index.js
> +  });
[OPTIONAL] One of the requirements hasn't been fulfilled yet, but I highly recommend working on it:

- [ ] The book should disappear and be deleted from the local storage when the user clicks the Delete button.

2022-10-28 10:10 UTC, merged